configured_endpoints: 45
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/plastic-labs%2Fhoncho-ae1fe9baaa0af0e1224c796f2f8eb266de0eb0642c3b3cbc589444d731af9d0f.yml
openapi_spec_hash: 8b9ef90dcf429784d2d0acf0f4d7ecfd
config_hash: 99bb2383e3fac6f9fccfd422345099a0
